package com.hmdp;

import com.hmdp.ai.QdrantKnowledgeClient;
import com.hmdp.config.AiKnowledgeProperties;
import com.hmdp.entity.Shop;
import com.hmdp.service.IShopService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.geo.Point;
import org.springframework.data.redis.connection.RedisGeoCommands;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.support.TransactionTemplate;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static com.hmdp.utils.RedisConstants.CACHE_SHOP_KEY;
import static com.hmdp.utils.RedisConstants.SHOP_GEO_KEY;

/**
 * One-off cleanup for the shops and blogs generated by DemoDataPreparationTest.
 *
 * Preview:
 * mvn -Dtest=DemoDataCleanupTest -Dcleanup.demo-data=true test
 *
 * Execute after checking the preview:
 * mvn -Dtest=DemoDataCleanupTest -Dcleanup.demo-data=true
 *     -Dcleanup.execute=true -Dcleanup.expected-shop-count=100 test
 */
@SpringBootTest
@ActiveProfiles("local")
@EnabledIfSystemProperty(named = "cleanup.demo-data", matches = "true")
class DemoDataCleanupTest {

    private static final int SHOP_TYPE_COUNT = 10;

    @Resource
    private JdbcTemplate jdbcTemplate;

    @Resource
    private TransactionTemplate transactionTemplate;

    @Resource
    private IShopService shopService;

    @Resource
    private StringRedisTemplate stringRedisTemplate;

    @Resource
    private QdrantKnowledgeClient qdrantKnowledgeClient;

    @Resource
    private AiKnowledgeProperties knowledgeProperties;

    @Test
    void cleanupGeneratedDemoData() {
        List<String> demoShopNames = new ArrayList<>(DemoDataPreparationTest.demoShopNames());
        List<Map<String, Object>> generatedShops = jdbcTemplate.queryForList(
                "SELECT id, name, type_id, create_time FROM tb_shop WHERE name IN ("
                        + placeholders(demoShopNames.size()) + ") ORDER BY id",
                demoShopNames.toArray());
        List<Long> shopIds = generatedShops.stream()
                .map(row -> ((Number) row.get("id")).longValue())
                .collect(Collectors.toList());
        List<Long> blogIds = findGeneratedBlogIds(shopIds);
        int voucherCount = countByShopIds("tb_voucher", shopIds);
        int syncTaskCount = countByShopIds("tb_ai_knowledge_sync_task", shopIds);

        printPreview(generatedShops, blogIds.size(), voucherCount, syncTaskCount);
        if (!Boolean.getBoolean("cleanup.execute")) {
            System.out.println("Preview only. No data was changed.");
            return;
        }

        int expectedShopCount = Integer.getInteger("cleanup.expected-shop-count", -1);
        if (expectedShopCount < 0 || generatedShops.size() != expectedShopCount) {
            throw new IllegalStateException("Cleanup aborted: expected generated shop count="
                    + expectedShopCount + ", actual=" + generatedShops.size());
        }
        if (voucherCount > 0) {
            throw new IllegalStateException("Cleanup aborted: generated shops own "
                    + voucherCount + " vouchers; review them manually before deletion");
        }

        transactionTemplate.executeWithoutResult(status -> {
            deleteBlogRows(blogIds);
            deleteByShopIds("tb_ai_knowledge_sync_task", shopIds);
            deleteByIds("tb_shop", shopIds);
        });

        clearRedisData(shopIds, blogIds);
        rebuildShopGeoIndex();
        if (Boolean.getBoolean("cleanup.delete-qdrant-points")) {
            deleteQdrantPoints(shopIds);
        } else {
            System.out.println("Qdrant points were not changed. Add "
                    + "-Dcleanup.delete-qdrant-points=true while Qdrant is available.");
        }

        System.out.printf("Cleanup completed: deleted shops=%d, blogs=%d, syncTasks=%d.%n",
                shopIds.size(), blogIds.size(), syncTaskCount);
    }

    private List<Long> findGeneratedBlogIds(List<Long> shopIds) {
        List<Long> ids = new ArrayList<>();
        if (!shopIds.isEmpty()) {
            ids.addAll(jdbcTemplate.queryForList(
                    "SELECT id FROM tb_blog WHERE shop_id IN (" + placeholders(shopIds.size()) + ")",
                    shopIds.toArray(),
                    Long.class));
        }
        return ids.stream().distinct().sorted().collect(Collectors.toList());
    }

    private int countByShopIds(String table, List<Long> shopIds) {
        if (shopIds.isEmpty()) {
            return 0;
        }
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + table + " WHERE shop_id IN ("
                        + placeholders(shopIds.size()) + ")",
                shopIds.toArray(),
                Integer.class);
        return count == null ? 0 : count;
    }

    private void deleteBlogRows(List<Long> blogIds) {
        if (blogIds.isEmpty()) {
            return;
        }
        Object[] args = blogIds.toArray();
        String placeholders = placeholders(blogIds.size());
        jdbcTemplate.update("DELETE FROM tb_blog_comments WHERE blog_id IN (" + placeholders + ")", args);
        jdbcTemplate.update("DELETE FROM tb_blog WHERE id IN (" + placeholders + ")", args);
    }

    private void deleteByShopIds(String table, List<Long> shopIds) {
        if (!shopIds.isEmpty()) {
            jdbcTemplate.update("DELETE FROM " + table + " WHERE shop_id IN ("
                    + placeholders(shopIds.size()) + ")", shopIds.toArray());
        }
    }

    private void deleteByIds(String table, List<Long> ids) {
        if (!ids.isEmpty()) {
            jdbcTemplate.update("DELETE FROM " + table + " WHERE id IN ("
                    + placeholders(ids.size()) + ")", ids.toArray());
        }
    }

    private void clearRedisData(List<Long> shopIds, List<Long> blogIds) {
        List<String> keys = new ArrayList<>();
        for (Long shopId : shopIds) {
            keys.add(CACHE_SHOP_KEY + shopId);
        }
        for (Long blogId : blogIds) {
            keys.add("blog:liked:" + blogId);
        }
        if (!keys.isEmpty()) {
            stringRedisTemplate.delete(keys);
        }
    }

    private void rebuildShopGeoIndex() {
        List<Shop> shops = shopService.list();
        for (int typeId = 1; typeId <= SHOP_TYPE_COUNT; typeId++) {
            String key = SHOP_GEO_KEY + typeId;
            stringRedisTemplate.delete(key);
            final int currentTypeId = typeId;
            List<RedisGeoCommands.GeoLocation<String>> locations = shops.stream()
                    .filter(shop -> shop.getTypeId() != null && shop.getTypeId() == currentTypeId)
                    .filter(shop -> shop.getX() != null && shop.getY() != null)
                    .map(shop -> new RedisGeoCommands.GeoLocation<>(
                            shop.getId().toString(),
                            new Point(shop.getX(), shop.getY())))
                    .collect(Collectors.toList());
            if (!locations.isEmpty()) {
                stringRedisTemplate.opsForGeo().add(key, locations);
            }
        }
    }

    private void deleteQdrantPoints(List<Long> shopIds) {
        for (Long shopId : shopIds) {
            try {
                qdrantKnowledgeClient.deletePoint(knowledgeProperties.getShopCollection(), shopId);
            } catch (Exception e) {
                throw new IllegalStateException("Failed to delete Qdrant point, shopId=" + shopId, e);
            }
        }
    }

    private void printPreview(List<Map<String, Object>> shops, int blogCount,
                              int voucherCount, int syncTaskCount) {
        System.out.printf("Cleanup preview: shops=%d, blogs=%d, vouchers=%d, syncTasks=%d.%n",
                shops.size(), blogCount, voucherCount, syncTaskCount);
        for (Map<String, Object> shop : shops) {
            System.out.printf("shopId=%s, typeId=%s, name=%s, createTime=%s%n",
                    shop.get("id"), shop.get("type_id"), shop.get("name"), shop.get("create_time"));
        }
    }

    private String placeholders(int count) {
        return String.join(",", Collections.nCopies(count, "?"));
    }
}
