package com.hmdp.evidence;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hmdp.config.AiEvaluationProperties;
import com.hmdp.dto.AiConversationCreateRequest;
import com.hmdp.dto.AiMessageSendRequest;
import com.hmdp.dto.Result;
import com.hmdp.dto.UserDTO;
import com.hmdp.entity.AiConversation;
import com.hmdp.entity.AiMessage;
import com.hmdp.entity.AiRequestLog;
import com.hmdp.entity.AiToolLog;
import com.hmdp.entity.AiTrace;
import com.hmdp.service.IAiConversationService;
import com.hmdp.service.IAiMessageService;
import com.hmdp.service.IAiRequestLogService;
import com.hmdp.service.IAiToolLogService;
import com.hmdp.service.IAiTraceService;
import com.hmdp.service.IUserService;
import com.hmdp.utils.UserHolder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

/**
 * Runs the existing public chat service against isolated, persisted conversations.
 *
 * This class is deliberately an outer test harness: it does not call or alter the
 * query rewriter, retrieval service, Agent runner, tool router, prompt builder, or
 * model client directly. Each prior turn is generated by the current Agent and saved
 * to tb_ai_message before the next turn is sent.
 */
@Slf4j
@Component
@Order(210)
@ConditionalOnProperty(prefix = "ai.evaluation", name = "conversation-enabled", havingValue = "true")
public class RagConversationEvaluationRunner implements ApplicationRunner {

    @Resource
    private AiEvaluationProperties properties;
    @Resource
    private IAiConversationService aiConversationService;
    @Resource
    private IAiMessageService aiMessageService;
    @Resource
    private IAiTraceService aiTraceService;
    @Resource
    private IAiRequestLogService aiRequestLogService;
    @Resource
    private IAiToolLogService aiToolLogService;
    @Resource
    private IUserService userService;
    @Resource
    private ObjectMapper objectMapper;

    @Override
    public void run(ApplicationArguments args) {
        try {
            runEvaluation();
        } catch (Exception e) {
            log.error("Conversation evaluation failed. Existing result files were left unchanged.", e);
        }
    }

    private void runEvaluation() throws Exception {
        Long userId = properties.getConversationUserId();
        if (userId == null || userService.getById(userId) == null) {
            throw new IllegalStateException("ai.evaluation.conversation-user-id must be an existing tb_user.id");
        }
        Path source = Paths.get(properties.getConversationCasesPath());
        List<CaseDefinition> cases = readCases(source, properties.getConversationCasesSplit());
        boolean retrySubset = hasRetrySubset();
        if (retrySubset) {
            cases = selectRetryCases(cases, properties.getConversationCaseIds());
        }
        int expected = retrySubset ? cases.size() : Math.max(1, properties.getConversationExpectedCaseCount());
        if (cases.size() != expected) {
            throw new IllegalStateException("Expected " + expected + " conversation cases, actual=" + cases.size());
        }
        List<Record> records = new ArrayList<>();
        for (CaseDefinition definition : cases) {
            records.add(runCase(userId, definition, retrySubset));
        }
        writeCsv(resolveOutputPath(properties.getConversationOutputPath(), retrySubset), records);
        writeReport(resolveOutputPath(properties.getConversationReportPath(), retrySubset), source, records);
        log.info("Conversation-level Agent evaluation completed, cases={}, retrySubset={}",
                records.size(), retrySubset);
    }

    private Record runCase(Long userId, CaseDefinition definition, boolean retrySubset) {
        Record record = new Record(definition);
        try {
            AiConversation conversation = createConversation(userId, definition.caseId, retrySubset);
            record.conversationId = conversation.getId();
            AwaitedTurn finalTurn = null;
            for (String turn : definition.turns) {
                finalTurn = sendAndAwait(userId, conversation.getId(), turn);
            }
            if (finalTurn == null) {
                throw new IllegalStateException("No turns in " + definition.caseId);
            }
            record.userMessageId = finalTurn.userMessageId;
            record.assistantMessageId = finalTurn.assistant.getId();
            record.messageStatus = finalTurn.assistant.getStatus();
            record.answer = finalTurn.assistant.getContent();
            fillTraceEvidence(record);
            record.traceComplete = "SUCCEEDED".equals(record.traceStatus)
                    || "FAILED".equals(record.traceStatus) || "CANCELLED".equals(record.traceStatus);
            record.executionCompleted = record.messageStatus != null
                    && record.messageStatus != AiMessage.STATUS_GENERATING && record.traceComplete;
            record.requiredToolsInvoked = record.requiredTools.stream().allMatch(record.actualTools::contains);
            record.expectedEntityMentioned = record.expectedShopNames.isEmpty()
                    || record.expectedShopNames.stream().map(this::normalize)
                    .anyMatch(normalize(record.answer)::contains);
            record.automaticPass = record.executionCompleted && "SUCCEEDED".equals(record.traceStatus)
                    && record.requiredToolsInvoked;
        } catch (Exception e) {
            record.error = safeError(e);
        }
        return record;
    }

    private AiConversation createConversation(Long userId, String caseId, boolean retrySubset) {
        AiConversationCreateRequest request = new AiConversationCreateRequest();
        String prefix = properties.getConversationTitlePrefix() == null ? "[E2E-EVAL]" : properties.getConversationTitlePrefix();
        if (retrySubset) {
            prefix = prefix + "-RETRY";
        }
        request.setTitle((prefix + " " + caseId).substring(0, Math.min(128, (prefix + " " + caseId).length())));
        Result result = withUser(userId, () -> aiConversationService.createConversation(request));
        if (!Boolean.TRUE.equals(result.getSuccess()) || !(result.getData() instanceof AiConversation)) {
            throw new IllegalStateException("Failed to create evaluation conversation: " + result.getErrorMsg());
        }
        return (AiConversation) result.getData();
    }

    private boolean hasRetrySubset() {
        return properties.getConversationCaseIds() != null
                && !properties.getConversationCaseIds().trim().isEmpty();
    }

    private List<CaseDefinition> selectRetryCases(List<CaseDefinition> allCases, String caseIds) {
        List<String> requestedIds = Arrays.stream(caseIds.split(","))
                .map(String::trim)
                .filter(this::notBlank)
                .distinct()
                .collect(Collectors.toList());
        if (requestedIds.isEmpty()) {
            throw new IllegalArgumentException("ai.evaluation.conversation-case-ids is empty");
        }
        Map<String, CaseDefinition> byId = allCases.stream()
                .collect(Collectors.toMap(item -> item.caseId, item -> item, (left, right) -> left,
                        LinkedHashMap::new));
        List<CaseDefinition> selected = new ArrayList<>();
        for (String caseId : requestedIds) {
            CaseDefinition definition = byId.get(caseId);
            if (definition == null) {
                throw new IllegalArgumentException("Unknown conversation evaluation case: " + caseId);
            }
            selected.add(definition);
        }
        return selected;
    }

    private Path resolveOutputPath(String configuredPath, boolean retrySubset) {
        Path path = Paths.get(configuredPath);
        if (!retrySubset) {
            return path;
        }
        String fileName = path.getFileName().toString();
        int dot = fileName.lastIndexOf('.');
        String retryName = dot < 0 ? fileName + "-retry" : fileName.substring(0, dot) + "-retry" + fileName.substring(dot);
        return path.resolveSibling(retryName);
    }

    private AwaitedTurn sendAndAwait(Long userId, Long conversationId, String question) throws InterruptedException {
        AiMessageSendRequest request = new AiMessageSendRequest();
        request.setContent(question);
        withUser(userId, () -> {
            aiConversationService.chat(conversationId, request);
            return null;
        });
        AiMessage assistant = aiMessageService.getOne(new QueryWrapper<AiMessage>()
                .eq("conversation_id", conversationId).eq("role", AiMessage.ROLE_ASSISTANT)
                .orderByDesc("id").last("LIMIT 1"));
        AiMessage user = aiMessageService.getOne(new QueryWrapper<AiMessage>()
                .eq("conversation_id", conversationId).eq("role", AiMessage.ROLE_USER)
                .orderByDesc("id").last("LIMIT 1"));
        if (assistant == null) {
            throw new IllegalStateException("Agent did not create an assistant message");
        }
        long deadline = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(turnTimeoutMs());
        while (System.nanoTime() < deadline) {
            assistant = aiMessageService.getById(assistant.getId());
            if (assistant != null && assistant.getStatus() != AiMessage.STATUS_GENERATING) {
                return new AwaitedTurn(user == null ? null : user.getId(), assistant);
            }
            Thread.sleep(100L);
        }
        throw new IllegalStateException("Timed out waiting for assistantMessageId=" + assistant.getId());
    }

    private void fillTraceEvidence(Record record) throws InterruptedException {
        long deadline = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(turnTimeoutMs());
        AiTrace trace = null;
        while (System.nanoTime() < deadline) {
            trace = aiTraceService.getOne(new QueryWrapper<AiTrace>()
                    .eq("assistant_message_id", record.assistantMessageId).eq("trace_type", "CHAT")
                    .orderByDesc("id").last("LIMIT 1"));
            if (trace != null && !"RUNNING".equals(trace.getStatus())) {
                break;
            }
            Thread.sleep(100L);
        }
        if (trace == null) {
            throw new IllegalStateException("Missing CHAT trace for assistantMessageId=" + record.assistantMessageId);
        }
        record.requestId = trace.getRequestId();
        record.traceId = trace.getTraceId();
        record.traceStatus = trace.getStatus();
        record.outcome = trace.getOutcome();
        record.errorStage = trace.getErrorStage();
        record.totalMs = trace.getTotalMs();
        AiRequestLog requestLog = aiRequestLogService.getOne(new QueryWrapper<AiRequestLog>()
                .eq("trace_id", record.traceId).eq("assistant_message_id", record.assistantMessageId)
                .eq("request_type", "chat").orderByDesc("id").last("LIMIT 1"));
        if (requestLog != null) {
            record.retrievalMs = requestLog.getRetrievalMs();
            record.toolMs = requestLog.getToolMs();
            record.firstTokenMs = requestLog.getFirstTokenMs();
            record.totalMs = requestLog.getTotalMs();
            record.inputTokens = requestLog.getInputTokens();
            record.outputTokens = requestLog.getOutputTokens();
        }
        List<AiToolLog> tools = aiToolLogService.list(new QueryWrapper<AiToolLog>()
                .eq("trace_id", record.traceId).eq("assistant_message_id", record.assistantMessageId).orderByAsc("id"));
        record.actualTools = tools.stream().map(AiToolLog::getToolName).filter(this::notBlank)
                .distinct().collect(Collectors.toList());
        record.toolEvidence = tools.stream().map(tool -> tool.getToolName() + ": " + limit(tool.getResultContent(), 1200))
                .collect(Collectors.joining("\n---\n"));
    }

    private List<CaseDefinition> readCases(Path source, String split) throws IOException {
        if (!Files.exists(source)) {
            throw new IllegalStateException("Conversation case file does not exist: " + source.toAbsolutePath());
        }
        List<String> lines = Files.readAllLines(source, StandardCharsets.UTF_8);
        if (lines.isEmpty()) {
            throw new IllegalStateException("Conversation case file is empty");
        }
        Map<String, Integer> indexes = indexes(csvValues(lines.get(0)));
        requireColumns(indexes, "id", "split", "scenario", "turns_json", "expected_shop_names", "required_tools");
        List<CaseDefinition> result = new ArrayList<>();
        for (int i = 1; i < lines.size(); i++) {
            if (lines.get(i).trim().isEmpty()) {
                continue;
            }
            List<String> row = csvValues(lines.get(i));
            if (!split.equalsIgnoreCase(value(row, indexes, "split"))) {
                continue;
            }
            CaseDefinition definition = new CaseDefinition();
            definition.caseId = value(row, indexes, "id");
            definition.scenario = value(row, indexes, "scenario");
            definition.turns = parseTurns(value(row, indexes, "turns_json"));
            definition.expectedShopNames = pipe(value(row, indexes, "expected_shop_names"));
            definition.requiredTools = pipe(value(row, indexes, "required_tools"));
            if (definition.turns.isEmpty()) {
                throw new IllegalStateException("No turns in case=" + definition.caseId);
            }
            result.add(definition);
        }
        return result;
    }

    private List<String> parseTurns(String json) throws IOException {
        JsonNode root = objectMapper.readTree(json);
        if (!root.isArray()) {
            throw new IllegalArgumentException("turns_json must be a JSON string array");
        }
        List<String> turns = new ArrayList<>();
        for (JsonNode node : root) {
            String text = node.asText("").trim();
            if (!text.isEmpty()) {
                turns.add(text);
            }
        }
        return turns;
    }

    private void writeCsv(Path path, List<Record> records) throws IOException {
        List<String> lines = new ArrayList<>();
        lines.add("case_id,scenario,conversation_id,user_message_id,assistant_message_id,request_id,trace_id,trace_status,outcome,error_stage,message_status,question,expected_shop_names,required_tools,actual_tools,required_tools_invoked,expected_entity_mentioned,execution_completed,automatic_pass,retrieval_ms,tool_ms,first_token_ms,total_ms,input_tokens,output_tokens,error,tool_evidence,manual_status,review_faithfulness,review_constraints,review_coverage,review_realtime_consistency,review_no_evidence_safety,review_failure_stage,review_notes,final_answer");
        for (Record record : records) {
            lines.add(csv(Arrays.asList(record.caseId, record.scenario, text(record.conversationId), text(record.userMessageId),
                    text(record.assistantMessageId), record.requestId, record.traceId, record.traceStatus, record.outcome,
                    record.errorStage, text(record.messageStatus), record.finalQuestion(), String.join("|", record.expectedShopNames),
                    String.join("|", record.requiredTools), String.join("|", record.actualTools), String.valueOf(record.requiredToolsInvoked),
                    String.valueOf(record.expectedEntityMentioned), String.valueOf(record.executionCompleted), String.valueOf(record.automaticPass),
                    text(record.retrievalMs), text(record.toolMs), text(record.firstTokenMs), text(record.totalMs), text(record.inputTokens),
                    text(record.outputTokens), record.error, record.toolEvidence, "PENDING", "", "", "", "", "", "", "", record.answer)));
        }
        Files.createDirectories(path.toAbsolutePath().getParent());
        Files.write(path, lines, StandardCharsets.UTF_8);
    }

    private void writeReport(Path path, Path source, List<Record> records) throws IOException {
        StringBuilder report = new StringBuilder();
        report.append("# 会话级 RAG 端到端评测\n\n")
                .append("> 生成时间：").append(LocalDateTime.now()).append('\n')
                .append("> 用例源：`").append(source).append("`。每个用例均创建独立会话，逐轮经现有 `chat()` 执行。\n")
                .append("> 自动检查只证明执行、Trace 和工具路由；最终事实正确性以 CSV 的 `review_*` 人工复核为准。\n\n")
                .append("|指标|结果|口径|\n|---|---:|---|\n")
                .append("|会话链路完成率|").append(rate(records, record -> record.executionCompleted)).append("|最终消息和 CHAT Trace 均结束|\n")
                .append("|根 Trace 成功率|").append(rate(records, record -> "SUCCEEDED".equals(record.traceStatus))).append("|最终轮 CHAT Trace 成功|\n")
                .append("|实时工具路由匹配率|").append(rate(withTools(records), record -> record.requiredToolsInvoked)).append("|仅统计声明 required_tools 的用例|\n")
                .append("|预期实体提及率|").append(rate(records, record -> record.expectedEntityMentioned)).append("|只检查提及，不等于事实正确|\n")
                .append("|P50 / P95 总耗时|").append(percentile(records, record -> record.totalMs, .5D)).append("ms / ")
                .append(percentile(records, record -> record.totalMs, .95D)).append("ms|最终轮 request log|\n")
                .append("|P50 / P95 首Token|").append(percentile(records, record -> record.firstTokenMs, .5D)).append("ms / ")
                .append(percentile(records, record -> record.firstTokenMs, .95D)).append("ms|最终轮 request log|\n\n")
                .append("## 人工复核\n\n填写 CSV 中 `review_faithfulness`、`review_constraints`、`review_coverage`、`review_realtime_consistency`、`review_no_evidence_safety` 与 `review_failure_stage`。\n");
        Files.createDirectories(path.toAbsolutePath().getParent());
        Files.write(path, report.toString().getBytes(StandardCharsets.UTF_8));
    }

    private <T> T withUser(Long userId, UserCall<T> call) {
        UserDTO user = new UserDTO();
        user.setId(userId);
        try {
            UserHolder.saveUser(user);
            return call.call();
        } finally {
            UserHolder.removeUser();
        }
    }

    private long turnTimeoutMs() { return Math.max(1000L, properties.getConversationTurnTimeoutMs()); }
    private List<Record> withTools(List<Record> records) { return records.stream().filter(record -> !record.requiredTools.isEmpty()).collect(Collectors.toList()); }
    private String rate(List<Record> records, RecordPredicate predicate) { if (records.isEmpty()) return "N/A"; long count = records.stream().filter(predicate::test).count(); return String.format(Locale.ROOT, "%.2f%% (%d/%d)", count * 100D / records.size(), count, records.size()); }
    private long percentile(List<Record> records, LongValue value, double p) { List<Long> values = records.stream().map(value::get).filter(v -> v != null && v >= 0).sorted().collect(Collectors.toList()); return values.isEmpty() ? 0L : values.get(Math.max(0, (int) Math.ceil(values.size() * p) - 1)); }
    private Map<String, Integer> indexes(List<String> headers) { Map<String, Integer> result = new LinkedHashMap<>(); for (int i = 0; i < headers.size(); i++) result.put(headers.get(i), i); return result; }
    private void requireColumns(Map<String, Integer> indexes, String... names) { for (String name : names) if (!indexes.containsKey(name)) throw new IllegalStateException("Missing source column: " + name); }
    private String value(List<String> row, Map<String, Integer> indexes, String key) { Integer i = indexes.get(key); return i == null || i >= row.size() ? "" : row.get(i); }
    private List<String> pipe(String value) { return value == null || value.trim().isEmpty() ? Collections.emptyList() : Arrays.stream(value.split("\\|")).map(String::trim).filter(this::notBlank).collect(Collectors.toList()); }
    private boolean notBlank(String value) { return value != null && !value.trim().isEmpty(); }
    private String normalize(String value) { return value == null ? "" : value.toLowerCase().replaceAll("[\\s\\p{P}\\p{S}]", ""); }
    private String text(Object value) { return value == null ? "" : String.valueOf(value); }
    private String limit(String value, int max) { if (value == null || value.length() <= max) return value == null ? "" : value; return value.substring(0, max - 3) + "..."; }
    private String safeError(Exception error) { return limit((error.getMessage() == null ? error.getClass().getSimpleName() : error.getMessage()).replaceAll("[\\r\\n]+", " "), 512); }
    private List<String> csvValues(String line) { List<String> values = new ArrayList<>(); StringBuilder value = new StringBuilder(); boolean quoted = false; for (int i = 0; i < line.length(); i++) { char current = line.charAt(i); if (current == '"') { if (quoted && i + 1 < line.length() && line.charAt(i + 1) == '"') { value.append('"'); i++; } else quoted = !quoted; } else if (current == ',' && !quoted) { values.add(value.toString()); value.setLength(0); } else value.append(current); } values.add(value.toString()); return values; }
    private String csv(List<String> values) { return values.stream().map(value -> { String safe = value == null ? "" : value; return safe.contains(",") || safe.contains("\"") || safe.contains("\n") ? "\"" + safe.replace("\"", "\"\"") + "\"" : safe; }).collect(Collectors.joining(",")); }

    private interface UserCall<T> { T call(); }
    private interface RecordPredicate { boolean test(Record record); }
    private interface LongValue { Long get(Record record); }
    private static class AwaitedTurn { private final Long userMessageId; private final AiMessage assistant; private AwaitedTurn(Long userMessageId, AiMessage assistant) { this.userMessageId = userMessageId; this.assistant = assistant; } }
    private static class CaseDefinition { private String caseId; private String scenario; private List<String> turns = Collections.emptyList(); private List<String> expectedShopNames = Collections.emptyList(); private List<String> requiredTools = Collections.emptyList(); }
    private static class Record {
        private final String caseId; private final String scenario; private final List<String> turns; private final List<String> expectedShopNames; private final List<String> requiredTools;
        private Long conversationId; private Long userMessageId; private Long assistantMessageId; private String requestId; private String traceId; private String traceStatus; private String outcome; private String errorStage; private Integer messageStatus; private List<String> actualTools = Collections.emptyList(); private boolean requiredToolsInvoked; private boolean expectedEntityMentioned; private boolean executionCompleted; private boolean traceComplete; private boolean automaticPass; private Long retrievalMs; private Long toolMs; private Long firstTokenMs; private Long totalMs; private Integer inputTokens; private Integer outputTokens; private String error; private String toolEvidence; private String answer;
        private Record(CaseDefinition definition) { caseId = definition.caseId; scenario = definition.scenario; turns = definition.turns; expectedShopNames = definition.expectedShopNames; requiredTools = definition.requiredTools; }
        private String finalQuestion() { return turns.isEmpty() ? "" : turns.get(turns.size() - 1); }
    }
}
